# Generated by Django 2.2.5 on 2019-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20190903_2232'),
        ('participantes', '0002_participante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
