# Generated by Django 2.2.5 on 2019-09-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_participante_atracoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='user',
        ),
    ]
