# Generated by Django 2.2.5 on 2019-09-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_atracoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='atracoes',
        ),
    ]
