# Generated by Django 2.2.5 on 2019-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da atração', max_length=100, verbose_name='Nome')),
                ('horario', models.DateTimeField()),
            ],
        ),
    ]
