# Generated by Django 2.2.5 on 2019-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0002_participante_user'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='participantes',
            field=models.ManyToManyField(to='participantes.Participante'),
        ),
    ]
