# Generated by Django 2.2.5 on 2019-09-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_atracoes'),
        ('atracoes', '0002_atracao_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='participantes',
        ),
        migrations.AddField(
            model_name='atracao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eventos.Evento'),
            preserve_default=False,
        ),
    ]
