# Generated by Django 2.2.5 on 2019-09-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20190903_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
    ]
